### PR TITLE
Rename getSkippedAsNotFailingStatus

### PR DESCRIPTION
**Pull request by damianszczepanik**

### CODE REVIEW

**Comment by chriscarpenter12** [comment]
What's the timeline of getting a release out with this change? It's currently flooding our Jenkins logs

**Comment by damianszczepanik** [comment]
Published

**Comment by sujithmathew93** [comment]
Hello @damianszczepanik, what we have seen with this newly added checkbox is that the value is not retained in the Jenkins Configuration. So once the checkbox is checked and the job configuration is saved, opening it again we are seeing that the checkbox has not retained this selection, hence not able to use the 'Mark skipped as not failing status' option.

**Comment by damianszczepanik** [comment]
Testing last version with that fix and could not reproduce the problem

**Pull request merged**
